export enum SOCKET_EVENT {
  Error = "error",
  Info = "info",
  GetGameSettings = "get game settings",
  GetPlayerList = "get player list",
  TakeCard = "take card",
  PlayCard = "play card",
  CardPlayed = "card played",
  ConsumeCard = "consume card",
  Overcharged = "overcharged",
  HitPointChanged = "hit point changed",
  ChargePointChanged = "charge point changed",
  StartTurn = "start turn",
  TakeSpell = "take spell",
  FindGame = "find game",
  PlayerEliminated = "player eliminated",
  RejectGame = "reject game",
  AcceptGame = "accept game",
  UpdateFindGameStatus = "update find game status",
  NewGame = "new game",
  Ready = "ready",
  GameOver = "game over",
  LeaveGame = "leave game",
  PlayerLeftGame = "player left game",
  ActivatePassive = "activate passive",
  Disconnect = "disconnect",
  Rename = "rename",
}
