enum SOCKET_EVENT {
  Error = "error",
  Info = "info",
  GetGameInfo = "get game info",
  GetPlayerList = "get player list",
  TakeCard = "take card",
  PlayCard = "play card",
  CardPlayed = "card played",
  ConsumeCard = "consume card",
  ChargePointBarOvercharged = "charge point bar overcharged",
  HitPointChanged = "hit point changed",
  ChargePointChanged = "charge point changed",
  StartTurn = "start turn",
  TakeSpell = "take spell",
  FindGame = "find game",
  Connected = "connected",
  PlayerEliminated = "player eliminated",
  Ready = "ready",
  GameFound = "game found",
  GameOver = "game over",
  LeaveGame = "leave game",
  PlayerLeftGame = "player left game",
  ActivatePassive = "activate passive",
}

export default SOCKET_EVENT;
